### PR TITLE
Fix Swift Package Tests

### LINKED ISSUE #15: Bundle unit test resources with SPM (blocked)
Mentioned by @robotive here: https://github.com/hsluv/hsluv-swift/pull/14

> As the current version of SPM doesn't support bundling resources, unit tests won't be running via SPM as the project is using a JSON resource file. As soon as [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) is implemented, this issue should be fixed.

### PR DESCRIPTION
**Pull request by robotive**
### Changes

• Fixes tests failing to run in SPM.
• Updates Travis config to use Xcode 12 and latest SDKs.
• Increases ver. to 2.2.0.

• Minor fixes in the README.

Closes #15.

### Notes

Requires Xcode 12, therefore it can't be merged until Xcode 12 is in beta.

### CODE REVIEW

**Comment by robotive** [comment]
@boronine This is good to go now, but has to wait for Xcode 12 to get out of beta, therefore I will keep it as a draft. I took the liberty of updating the version to 2.2.0, as this is a breaking change, but that commit can be removed if needed.

**Comment by boronine** [comment]
Thanks @robotive! Will merge when this is ready.

**Comment by robotive** [comment]
@boronine This can be merged now. Thanks!

**Comment by boronine** [comment]
Magnificent, tests pass! Thank you @robotive

**Pull request merged**
