### PR TITLE
Swift Package Manager Support

### PR DESCRIPTION
**Pull request by robotive**
### Main Changes

• Adds support for Swift Package Manager.

### Auxiliary Changes

• Updated Xcode project to latest/recommended settings.
• Updated project structure to match default SPM structure.
• Updated Travis config.

### Notes

• As the current version of SPM doesn't support bundling resources, unit tests won't be running via SPM as the project is using a JSON resource file. As soon as [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) is implemented, this issue should be fixed.
• Minor changes were done to the podspec to account for the project structure changes, but these changes were not tested as I am not using CocoaPods.
• The Readme file was also updated to add notes about SPM. They mention the version 2.1.0 which I thought would make sense to tag the changes with after they are merged into master.

```
Closes Issue #11.
```

### CODE REVIEW

**Comment by robotive** [comment]
@boronine Should be good to go now.

**Comment by boronine** [comment]
Amazing work! Thank you @robotive 🎉

**Comment by vyshane** [comment]
Thanks indeed! When will `v2.1.0` be released?

**Comment by boronine** [comment]
@vyshane I just pushed the tag, can you let me know if this enables you to fetch it with SPM? I'm also looking into publishing the CocoaPod version now.

**Comment by boronine** [comment]
CocoaPod published: https://cocoapods.org/pods/HSLuvSwift

**Comment by robotive** [comment]
@boronine Thanks for merging!

One small thing, while I don't use Cocoapods I've noticed a change you did to the pod spec here: https://github.com/hsluv/hsluv-swift/blob/a550a6aeaaf48986ea3f57d5adb77818830dc513/HSLuvSwift.podspec#L16

Small correction needed thought, Swift should be set to version 5.0.

**Comment by boronine** [comment]
Thanks for the catch, updated

**Comment by vyshane** [comment]
> @vyshane I just pushed the tag, can you let me know if this enables you to fetch it with SPM?

@boronine, yep, I can confirm that installation via SPM works 👍

**Pull request merged**
